# Site settings
title: NURSHALEHA
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://nurshaleha.github.io'
baseurl: '/nurshaleha.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'nurshaleha'
  email: nursaleha138@yahoo.co.id
  twitter_username: leha
  facebook_username: Nur shaleha
  github_username:  nurshaleha
  linkedin_username:  nurshaleha

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
